SELECT [reservation_id]
      ,[location_name]
      ,[reserved_by_pallet_id]
      ,[username]
      ,[reservation_type]
      ,[reserved_at]
      ,[expires_at]
      ,[aisle]
  FROM [WMS_DB].[views].[Reserved_Locations]